title: Blog & Philosophy
email: bojkoburgas@abv.bg
description: My opinion on topics that I find interesting. I bit of journaling about my life in Burgas / Bulgaria can be found too.
baseurl: "bojkos-thoughts"
url: ""
twitter_username: BozhidarSot
github_username:  Bojidar06

theme: minima
plugins:
  - jekyll-feed
